### ISSUE TITLE
Why is it blocked？

### ISSUE THREAD

**Issue by wujilingfeng** [haskell/stm#47]
I run the following  code,but it didn't print "end".
``` haskell
main=do
  initFFmpeg
  (getFrame,cleanup)<- imageReaderTime (File "bunny.mp4"):: IO (IO (Maybe (Image PixelRGB8,Double)),IO() )
  queue<- atomically $ newTQueue
  forkIO $ do
      fra<- getFrame 
      atomically $ writeTQueue queue 1
      putStrLn "end "  
``` 
Is it because of running out of memory？

--- 
When I comment out `fra<-getFrame`, It runs well.When I comment out `atomically $ writeTQueue queue 1` ,it also runs well.

**Comment by Fuuzetsu** [comment]
Does it actually block? If this is your whole program, I would expect it to exit straight away because there's nothing waiting on the thread you just forked and we reach end of `main`.

Can you provide an example that's a bit easier to work with? How are you verifying it's actually blocking and not just your program ending before the thread reaches the `putStrLn "end "`? I suspect when you're removing the `fra<- getFrame` or the `atomically $ writeTQueue queue 1` then it makes the thread do much less work and it might be managing to reach the print statement before the program finishes.

**Comment by wujilingfeng** [comment]
> Does it actually block? If this is your whole program, I would expect it to exit straight away because there's nothing waiting on the thread you just forked and we reach end of `main`.
> 
> Can you provide an example that's a bit easier to work with? How are you verifying it's actually blocking and not just your program ending before the thread reaches the `putStrLn "end "`? I suspect when you're removing the `fra<- getFrame` or the `atomically $ writeTQueue queue 1` then it makes the thread do much less work and it might be managing to reach the print statement before the program finishes.

I'm sorry, I think the cause is  main thread ended prematurely.

**Comment by Fuuzetsu** [comment]
>I'm sorry, I think the cause is main thread ended prematurely.

I see, so I guess we can close the ticket.

You can use something like the [async](https://hackage.haskell.org/package/async-2.2.3) library to make it easy to wait on threads, or you can use some other mechanism such as TVar/MVar to wait though that's a bit more tricky to get right.

Please re-open if you still think there's some issue with `stm`.
